name: Deploy to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'registrar-ai-frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Change to frontend directory
      run: cd registrar-ai-frontend

    - name: Install Dependencies
      run: npm install
      working-directory: ./registrar-ai-frontend

    - name: Build
      run: npm run build

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25.1.1
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
